Updated GDSC-Lead Map
abhinavsri360/GDSC-Lead-Map pull request #117
Opened 2021-08-11 10:58 UTC by James7881

Fixes #

## Proposed Changes

-
-
-

2021-08-11 16:14 UTC, aravindvnair99 requested changes

2021-08-11 16:14 UTC, aravindvnair99 commented on src/components/json/worldData.js
> +
```suggestion
```

2021-08-11 16:19 UTC, James7881 commented
I submitted Jamsher Shekh details,
This code is not submitted by me

On Wed, Aug 11, 2021, 9:44 PM Aravind Nair ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/components/json/worldData.js
> <https://github.com/abhinavsri360/GDSC-Lead-Map/pull/117#discussion_r686979793>
> :
>
> > @@ -1046,7 +1047,22 @@ const data = [
>
>          "linkedin": "https://linkedin.com/in/sanjaydevtech",
>
>          "twitter": "https://twitter.com/SanjayDevTech",
>
>          "portfolio": "https://sanjaydevtech.github.io/"
>
> -	}
>
> +	},
>
> +	
>
>
> ⬇️ Suggested change
>
> -	
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/abhinavsri360/GDSC-Lead-Map/pull/117#pullrequestreview-727684924>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AONBLYHLEHL3OAVPVTLA2NTT4KOVXANCNFSM5B6F2I7A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-12 06:12 UTC, abhinavsri360 requested changes
@James7881 
Your photograph is missing in the repository, do add that as well.

2021-08-12 20:57 UTC, James7881 commented
photo added

2021-08-13 16:09 UTC, abhinavsri360 approved these changes
Looks good to me now.

2021-08-13 16:11 UTC, merged