added AsishRaju
abhinavsri360/GDSC-Lead-Map pull request #13
Opened 2021-04-11 18:42 UTC by AsishRaju

## Proposed Changes

-  Added my pic in `src\photos\AsishRaju.jpg`
-  Added my details in `src\components\json\worldData.js`

2021-04-11 22:28 UTC, aravindvnair99 commented on src/components/json/worldData.js
> +		skills: ["Full Stack Web", "UI/UX",],
```suggestion
		skills: ["Web Dev", "UI/UX",],
```

2021-04-11 22:29 UTC, aravindvnair99 commented on src/components/json/worldData.js
> +		linkedin: "https://www.linkedin.com/in/asishraju/",
```suggestion
		linkedin: "https://linkedin.com/in/asishraju",
```

2021-04-11 22:29 UTC, aravindvnair99 requested changes
@AsishRaju You have used an invalid skill type.

2021-04-12 02:06 UTC, AsishRaju commented
@aravindvnair99 changes done 👍🏻

2021-04-12 03:13 UTC, abhinavsri360 approved these changes
Great work!

2021-04-12 03:13 UTC, merged