Pushing my data to the GDSC-Lead Map
abhinavsri360/GDSC-Lead-Map pull request #138
Opened 2022-09-10 16:59 UTC by JuliusKanneh

Fixes #

## Proposed Changes

-
-
-

2022-09-10 17:00 UTC, aravindvnair99 requested changes
@JuliusKanneh import isn't correct

2022-09-10 17:00 UTC, aravindvnair99 commented on src/components/json/worldData.js
> +import abhinavsri360 from "../../photos/JuliusKanneh.jpg";
```suggestion
import JuliusKanneh from "../../photos/JuliusKanneh.jpg";
```

2022-09-10 17:01 UTC, aravindvnair99 commented on src/components/json/worldData.js
> +		skills: ["Web Dev", "IOT"],
```suggestion
		skills: ["Web Dev", "IoT"],
```

2022-10-22 08:47 UTC, abhinavsri360 commented
Thanks, @JuliusKanneh for submitting your profile. Thanks, @aravindvnair99 for reviewing.
Sorry for the late response.

2022-10-22 08:47 UTC, merged