adding Abhinav T B
abhinavsri360/GDSC-Lead-Map pull request #49
Opened 2021-04-12 18:31 UTC by abhinav-TB

Fixes #

## Proposed Changes

-
-
-

2021-04-12 18:45 UTC, aravindvnair99 commented on src/components/json/worldData.js
> +                "chapterName": "cochin-university-of-science-and-technology",
```suggestion
                "chapterName": "Cochin University of Science and Technology",
```

2021-04-12 18:46 UTC, aravindvnair99 requested changes
@abhinav-TB This PR is proper. Just one minor change. You can accept the suggestion and commit, after which your PR will be merged.

2021-04-12 18:49 UTC, abhinav-TB commented
@aravindvnair99  done

2021-04-12 18:49 UTC, aravindvnair99 approved these changes

2021-04-13 03:08 UTC, abhinavsri360 approved these changes
Thanks for adding yourself!

2021-04-13 03:11 UTC, merged