DSC AEC
abhinavsri360/GDSC-Lead-Map pull request #72
Opened 2021-04-15 03:47 UTC by subratkishoredutta

Fixes #

## Proposed Changes

-
-
-

2021-04-15 04:42 UTC, abhinavsri360 requested changes
Moreover, can you please pull the changes and update the PR?

2021-04-15 04:42 UTC, abhinavsri360 commented on src/components/json/worldData.js
> +		photo: subrat,
this is supposed to be
```
photo: subratkishoredutta
```

2021-04-16 06:23 UTC, aravindvnair99 commented on src/components/json/worldData.js
> +		skills: ["DL","ML"],
```suggestion
		skills: ["AI/ML"],
```

2021-04-16 06:24 UTC, aravindvnair99 requested changes
@subratkishoredutta Only use skills mentioned in the guidelines.

2021-04-16 06:25 UTC, aravindvnair99 commented on src/components/json/worldData.js
> +		linkedin: "https://www.linkedin.com/in/subrat-kishore-dutta-70a9a316b/",
```suggestion
		linkedin: "https://linkedin.com/in/subrat-kishore-dutta-70a9a316b",
```

2021-04-16 06:34 UTC, aravindvnair99 approved these changes

2021-04-16 06:37 UTC, abhinavsri360 approved these changes
Thanks for adding yourself!

2021-04-16 06:42 UTC, subratkishoredutta commented
> Thanks for adding yourself!

thanks for this platform

2021-04-16 06:43 UTC, merged

2021-04-16 06:43 UTC, abhinavsri360 commented
> > Thanks for adding yourself!
> 
> thanks for this platform

You are Welcome 😄