Removed Quotes
abhinavsri360/GDSC-Lead-Map pull request #83
Opened 2021-04-17 16:16 UTC by akshita2k

Fixes #

## Proposed Changes

-
-
-

2021-04-17 17:38 UTC, aravindvnair99 requested changes

2021-04-17 17:38 UTC, aravindvnair99 commented on src/components/json/worldData.js
> +        bio: "I enjoy learning and exploring new vistas of Technology while also sharing the knowledge among my peers!.",
```suggestion
        bio: "I enjoy learning and exploring new vistas of Technology while also sharing the knowledge among my peers!",
```

2021-04-17 17:38 UTC, aravindvnair99 commented on src/components/json/worldData.js
> +        linkedin: "https://www.linkedin.com/in/akshita-sharma-15a703111",
```suggestion
        linkedin: "https://linkedin.com/in/akshita-sharma-15a703111",
```

2021-04-17 17:38 UTC, aravindvnair99 commented on src/components/json/worldData.js
> +        instagram: "https://www.instagram.com/akshi_4446",
```suggestion
        instagram: "https://instagram.com/akshi_4446",
```

2021-04-18 02:35 UTC, abhinavsri360 approved these changes
Looks good to me now. Thanks for adding yourself!

2021-04-18 02:39 UTC, merged