Update worldData.js
abhinavsri360/GDSC-Lead-Map pull request #87
Opened 2021-04-17 18:01 UTC by nehasangeetajha

Fixes #

## Proposed Changes

-
-
-

2021-04-17 18:08 UTC, aravindvnair99 commented on src/components/json/worldData.js
> +import sangeetajha from "../../photos/SangeetaJha.png";
```suggestion
import sangeetajha from "../../photos/SangeetaJha.jpg";
```

2021-04-17 18:08 UTC, aravindvnair99 requested changes
@nehasangeetajha Please add the picture to this PR itself and close #86. Also, it should be a `jpg` file. Please follow the [guidelines mentioned](https://github.com/abhinavsri360/GDSC-Lead-Map/blob/main/CONTRIBUTING.md).

2021-04-18 02:43 UTC, abhinavsri360 requested changes
Data Looks good to me, do add our picture in this PR itself 😄

2021-04-18 13:19 UTC, nehasangeetajha commented
Done!

2021-04-18 13:19 UTC, aravindvnair99 approved these changes

2021-04-18 16:42 UTC, abhinavsri360 approved these changes
Thanks for adding yourself.

2021-04-18 16:42 UTC, merged